name: Helm Chart Publish
on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Helm
        uses: azure/setup-helm@v1.1
        with:
          version: v3.7.0

      # - name: Configure AWS
        # uses: aws-actions/configure-aws-credentials@v4
        # with:
          # aws-region: ${{ secrets.AWS_REGION }}
          # role-to-assume: ${{ secrets.AWS_ROLE }}
          # role-session-name: GitHubActionsAWSAccess

      # - name: ECR Login
        # run: |
          # aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
          # helm registry login \
            # --username AWS \
            # --password-stdin ${{ steps.login-ecr.outputs.registry }}

      # - name: Create ECR Repository
        # run: |
          # aws ecr describe-repositories \
            # --repository-names ${GITHUB_REPOSITORY#*/} || \
          # aws ecr create-repository \
            # --repository-name ${GITHUB_REPOSITORY#*/}

      # - name: Package and Push to ECR
        # run: |
          # helm package bx-tmpl-node-rest-chart
          # helm push bx-tmpl-node-rest-chart-*.tgz oci://${{ steps.login-ecr.outputs.registry }}/

      - name: Package Helm Chart
        run: |
          mkdir -p .cr-release-packages
          helm package charts --destination .cr-release-packages

      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
      
      - name: Update Repository
        run: |
          cp .cr-release-packages/*.tgz gh-pages/
          cd gh-pages
          helm repo index . --url https://brsalcedom.github.io/${{ github.event.repository.name }}/ --merge index.yaml
          
          echo "---
          layout: none
          ---
          <!DOCTYPE html>
          <html>
          <head><title>Blue Express Helm Charts</title></head>
          <body><pre>{{ content }}</pre></body>
          </html>" > _config.yml
          git config user.name "GitHub Actions Bot"
          git config user.email "yourbot@yourorg.com"
          git add .
          git commit -m "Update Helm repository" 
          git push origin gh-pages